export const countryData = [
  { name: 'Afghanistan', abbreviation: 'AF', code: '+93' },
  { name: 'Albania', abbreviation: 'AL', code: '+355' },
  { name: 'Algeria', abbreviation: 'DZ', code: '+213' },
  { name: 'Andorra', abbreviation: 'AD', code: '+376' },
  { name: 'Angola', abbreviation: 'AO', code: '+244' },
  { name: 'Antigua and Barbuda', abbreviation: 'AG', code: '+1 (268)' },
  { name: 'Argentina', abbreviation: 'AR', code: '+54' },
  { name: 'Armenia', abbreviation: 'AM', code: '+374' },
  { name: 'Australia', abbreviation: 'AU', code: '+61' },
  { name: 'Austria', abbreviation: 'AT', code: '+43' },
  { name: 'Azerbaijan', abbreviation: 'AZ', code: '+994' },
  { name: 'Bahamas', abbreviation: 'BS', code: '+1 (242)' },
  { name: 'Bahrain', abbreviation: 'BH', code: '+973' },
  { name: 'Bangladesh', abbreviation: 'BD', code: '+880' },
  { name: 'Barbados', abbreviation: 'BB', code: '+1 (246)' },
  { name: 'Belarus', abbreviation: 'BY', code: '+375' },
  { name: 'Belgium', abbreviation: 'BE', code: '+32' },
  { name: 'Belize', abbreviation: 'BZ', code: '+501' },
  { name: 'Benin', abbreviation: 'BJ', code: '+229' },
  { name: 'Bhutan', abbreviation: 'BT', code: '+975' },
  { name: 'Bolivia', abbreviation: 'BO', code: '+591' },
  { name: 'Bosnia and Herzegovina', abbreviation: 'BA', code: '+387' },
  { name: 'Botswana', abbreviation: 'BW', code: '+267' },
  { name: 'Brazil', abbreviation: 'BR', code: '+55' },
  { name: 'Brunei', abbreviation: 'BN', code: '+673' },
  { name: 'Bulgaria', abbreviation: 'BG', code: '+359' },
  { name: 'Burkina Faso', abbreviation: 'BF', code: '+226' },
  { name: 'Burundi', abbreviation: 'BI', code: '+257' },
  { name: 'Cambodia', abbreviation: 'KH', code: '+855' },
  { name: 'Cameroon', abbreviation: 'CM', code: '+237' },
  { name: 'Canada', abbreviation: 'CA', code: '+1' },
  { name: 'Cape Verde', abbreviation: 'CV', code: '+238' },
  { name: 'Central African Republic', abbreviation: 'CF', code: '+236' },
  { name: 'Chad', abbreviation: 'TD', code: '+235' },
  { name: 'Chile', abbreviation: 'CL', code: '+56' },
  { name: 'China', abbreviation: 'CN', code: '+86' },
  { name: 'Colombia', abbreviation: 'CO', code: '+57' },
  { name: 'Comoros', abbreviation: 'KM', code: '+269' },
  { name: 'Congo', abbreviation: 'CG', code: '+242' },
  { name: 'Costa Rica', abbreviation: 'CR', code: '+506' },
  { name: 'Croatia', abbreviation: 'HR', code: '+385' },
  { name: 'Cuba', abbreviation: 'CU', code: '+53' },
  { name: 'Cyprus', abbreviation: 'CY', code: '+357' },
  { name: 'Czech Republic', abbreviation: 'CZ', code: '+420' },
  { name: 'Denmark', abbreviation: 'DK', code: '+45' },
  { name: 'Djibouti', abbreviation: 'DJ', code: '+253' },
  { name: 'Dominica', abbreviation: 'DM', code: '+1 (767)' },
  { name: 'Dominican Republic', abbreviation: 'DO', code: '+1 (809, 829, 849)' },
  { name: 'East Timor (Timor-Leste)', abbreviation: 'TL', code: '+670' },
  { name: 'Ecuador', abbreviation: 'EC', code: '+593' },
  { name: 'Egypt', abbreviation: 'EG', code: '+20' },
  { name: 'El Salvador', abbreviation: 'SV', code: '+503' },
  { name: 'Equatorial Guinea', abbreviation: 'GQ', code: '+240' },
  { name: 'Eritrea', abbreviation: 'ER', code: '+291' },
  { name: 'Estonia', abbreviation: 'EE', code: '+372' },
  { name: 'Ethiopia', abbreviation: 'ET', code: '+251' },
  { name: 'Fiji', abbreviation: 'FJ', code: '+679' },
  { name: 'Finland', abbreviation: 'FI', code: '+358' },
  { name: 'France', abbreviation: 'FR', code: '+33' },
  { name: 'Gabon', abbreviation: 'GA', code: '+241' },
  { name: 'Gambia', abbreviation: 'GM', code: '+220' },
  { name: 'Georgia', abbreviation: 'GE', code: '+995' },
  { name: 'Germany', abbreviation: 'DE', code: '+49' },
  { name: 'Ghana', abbreviation: 'GH', code: '+233' },
  { name: 'Greece', abbreviation: 'GR', code: '+30' },
  { name: 'Grenada', abbreviation: 'GD', code: '+1 (473)' },
  { name: 'Guatemala', abbreviation: 'GT', code: '+502' },
  { name: 'Guinea', abbreviation: 'GN', code: '+224' },
  { name: 'Guinea-Bissau', abbreviation: 'GW', code: '+245' },
  { name: 'Guyana', abbreviation: 'GY', code: '+592' },
  { name: 'Haiti', abbreviation: 'HT', code: '+509' },
  { name: 'Honduras', abbreviation: 'HN', code: '+504' },
  { name: 'Hungary', abbreviation: 'HU', code: '+36' },
  { name: 'Iceland', abbreviation: 'IS', code: '+354' },
  { name: 'India', abbreviation: 'IN', code: '+91' },
  { name: 'Indonesia', abbreviation: 'ID', code: '+62' },
  { name: 'Iran', abbreviation: 'IR', code: '+98' },
  { name: 'Iraq', abbreviation: 'IQ', code: '+964' },
  { name: 'Ireland', abbreviation: 'IE', code: '+353' },
  { name: 'Israel', abbreviation: 'IL', code: '+972' },
  { name: 'Italy', abbreviation: 'IT', code: '+39' },
  { name: 'Ivory Coast', abbreviation: 'CI', code: '+225' },
  { name: 'Jamaica', abbreviation: 'JM', code: '+1 (876)' },
  { name: 'Japan', abbreviation: 'JP', code: '+81' },
  { name: 'Jordan', abbreviation: 'JO', code: '+962' },
  { name: 'Kazakhstan', abbreviation: 'KZ', code: '+7' },
  { name: 'Kenya', abbreviation: 'KE', code: '+254' },
  { name: 'Kiribati', abbreviation: 'KI', code: '+686' },
  { name: 'Kuwait', abbreviation: 'KW', code: '+965' },
  { name: 'Kyrgyzstan', abbreviation: 'KG', code: '+996' },
  { name: 'Laos', abbreviation: 'LA', code: '+856' },
  { name: 'Latvia', abbreviation: 'LV', code: '+371' },
  { name: 'Lebanon', abbreviation: 'LB', code: '+961' },
  { name: 'Lesotho', abbreviation: 'LS', code: '+266' },
  { name: 'Liberia', abbreviation: 'LR', code: '+231' },
  { name: 'Libya', abbreviation: 'LY', code: '+218' },
  { name: 'Liechtenstein', abbreviation: 'LI', code: '+423' },
  { name: 'Lithuania', abbreviation: 'LT', code: '+370' },
  { name: 'Luxembourg', abbreviation: 'LU', code: '+352' },
  { name: 'North Macedonia', abbreviation: 'MK', code: '+389' },
  { name: 'Madagascar', abbreviation: 'MG', code: '+261' },
  { name: 'Malawi', abbreviation: 'MW', code: '+265' },
  { name: 'Malaysia', abbreviation: 'MY', code: '+60' },
  { name: 'Maldives', abbreviation: 'MV', code: '+960' },
  { name: 'Mali', abbreviation: 'ML', code: '+223' },
  { name: 'Malta', abbreviation: 'MT', code: '+356' },
  { name: 'Marshall Islands', abbreviation: 'MH', code: '+692' },
  { name: 'Mauritania', abbreviation: 'MR', code: '+222' },
  { name: 'Mauritius', abbreviation: 'MU', code: '+230' },
  { name: 'Mexico', abbreviation: 'MX', code: '+52' },
  { name: 'Micronesia', abbreviation: 'FM', code: '+691' },
  { name: 'Moldova', abbreviation: 'MD', code: '+373' },
  { name: 'Monaco', abbreviation: 'MC', code: '+377' },
  { name: 'Mongolia', abbreviation: 'MN', code: '+976' },
  { name: 'Montenegro', abbreviation: 'ME', code: '+382' },
  { name: 'Morocco', abbreviation: 'MA', code: '+212' },
  { name: 'Mozambique', abbreviation: 'MZ', code: '+258' },
  { name: 'Myanmar (Burma)', abbreviation: 'MM', code: '+95' },
  { name: 'Namibia', abbreviation: 'NA', code: '+264' },
  { name: 'Nauru', abbreviation: 'NR', code: '+674' },
  { name: 'Nepal', abbreviation: 'NP', code: '+977' },
  { name: 'Netherlands', abbreviation: 'NL', code: '+31' },
  { name: 'New Zealand', abbreviation: 'NZ', code: '+64' },
  { name: 'Nicaragua', abbreviation: 'NI', code: '+505' },
  { name: 'Niger', abbreviation: 'NE', code: '+227' },
  { name: 'Nigeria', abbreviation: 'NG', code: '+234' },
  { name: 'North Korea', abbreviation: 'KP', code: '+850' },
  { name: 'Norway', abbreviation: 'NO', code: '+47' },
  { name: 'Oman', abbreviation: 'OM', code: '+968' },
  { name: 'Pakistan', abbreviation: 'PK', code: '+92' },
  { name: 'Palau', abbreviation: 'PW', code: '+680' },
  { name: 'Palestine', abbreviation: 'PS', code: '+970' },
  { name: 'Panama', abbreviation: 'PA', code: '+507' },
  { name: 'Papua New Guinea', abbreviation: 'PG', code: '+675' },
  { name: 'Paraguay', abbreviation: 'PY', code: '+595' },
  { name: 'Peru', abbreviation: 'PE', code: '+51' },
  { name: 'Philippines', abbreviation: 'PH', code: '+63' },
  { name: 'Poland', abbreviation: 'PL', code: '+48' },
  { name: 'Portugal', abbreviation: 'PT', code: '+351' },
  { name: 'Qatar', abbreviation: 'QA', code: '+974' },
  { name: 'Romania', abbreviation: 'RO', code: '+40' },
  { name: 'Russia', abbreviation: 'RU', code: '+7' },
  { name: 'Rwanda', abbreviation: 'RW', code: '+250' },
  { name: 'Saint Kitts and Nevis', abbreviation: 'KN', code: '+1 (869)' },
  { name: 'Saint Lucia', abbreviation: 'LC', code: '+1 (758)' },
  { name: 'Saint Vincent and the Grenadines', abbreviation: 'VC', code: '+1 (784)' },
  { name: 'Samoa', abbreviation: 'WS', code: '+685' },
  { name: 'San Marino', abbreviation: 'SM', code: '+378' },
  { name: 'Sao Tome and Principe', abbreviation: 'ST', code: '+239' },
  { name: 'Saudi Arabia', abbreviation: 'SA', code: '+966' },
  { name: 'Senegal', abbreviation: 'SN', code: '+221' },
  { name: 'Serbia', abbreviation: 'RS', code: '+381' },
  { name: 'Seychelles', abbreviation: 'SC', code: '+248' },
  { name: 'Sierra Leone', abbreviation: 'SL', code: '+232' },
  { name: 'Singapore', abbreviation: 'SG', code: '+65' },
  { name: 'Slovakia', abbreviation: 'SK', code: '+421' },
  { name: 'Slovenia', abbreviation: 'SI', code: '+386' },
  { name: 'Solomon Islands', abbreviation: 'SB', code: '+677' },
  { name: 'Somalia', abbreviation: 'SO', code: '+252' },
  { name: 'South Africa', abbreviation: 'ZA', code: '+27' },
  { name: 'South Korea', abbreviation: 'KR', code: '+82' },
  { name: 'South Sudan', abbreviation: 'SS', code: '+211' },
  { name: 'Spain', abbreviation: 'ES', code: '+34' },
  { name: 'Sri Lanka', abbreviation: 'LK', code: '+94' },
  { name: 'Sudan', abbreviation: 'SD', code: '+249' },
  { name: 'Suriname', abbreviation: 'SR', code: '+597' },
  { name: 'Swaziland', abbreviation: 'SZ', code: '+268' },
  { name: 'Sweden', abbreviation: 'SE', code: '+46' },
  { name: 'Switzerland', abbreviation: 'CH', code: '+41' },
  { name: 'Syria', abbreviation: 'SY', code: '+963' },
  { name: 'Taiwan', abbreviation: 'TW', code: '+886' },
  { name: 'Tajikistan', abbreviation: 'TJ', code: '+992' },
  { name: 'Tanzania', abbreviation: 'TZ', code: '+255' },
  { name: 'Thailand', abbreviation: 'TH', code: '+66' },
  { name: 'Togo', abbreviation: 'TG', code: '+228' },
  { name: 'Tonga', abbreviation: 'TO', code: '+676' },
  { name: 'Trinidad and Tobago', abbreviation: 'TT', code: '+1 (868)' },
  { name: 'Tunisia', abbreviation: 'TN', code: '+216' },
  { name: 'Turkey', abbreviation: 'TR', code: '+90' },
  { name: 'Turkmenistan', abbreviation: 'TM', code: '+993' },
  { name: 'Tuvalu', abbreviation: 'TV', code: '+688' },
  { name: 'Uganda', abbreviation: 'UG', code: '+256' },
  { name: 'Ukraine', abbreviation: 'UA', code: '+380' },
  { name: 'United Arab Emirates', abbreviation: 'AE', code: '+971' },
  { name: 'United Kingdom', abbreviation: 'GB', code: '+44' },
  { name: 'Uruguay', abbreviation: 'UY', code: '+598' },
  { name: 'Uzbekistan', abbreviation: 'UZ', code: '+998' },
  { name: 'Vanuatu', abbreviation: 'VU', code: '+678' },
  { name: 'Vatican City', abbreviation: 'VA', code: '+379' }, // Vatican City's code is unique
  // Add more countries with abbreviations and codes here...
];
