export const cardData = [
  {
    id: 1,
    imageSrc: '/assets/reviews/rating-picture.png',
    title: 'The Complete Ruby on Rails Developer Course',
    author: 'Mark Essien',
    avgRating: 4.7,
    ratingNo: 1173,
    price: 18000,
  },
  {
    id: 2,
    imageSrc: '/assets/reviews/rating-picture-2.png',
    title: 'PHP for Beginners - Become a PHP Master',
    author: 'Mark Essien',
    avgRating: 4.7,
    ratingNo: 1173,
    price: 8000,
  },
  {
    id: 3,
    imageSrc: '/assets/reviews/rating-picture-3.png',
    title: 'Dissecting Ruby on Rails 5',
    author: 'Mark Essien',
    avgRating: 4.7,
    ratingNo: 123,
    price: 7500,
  },
  {
    id: 4,
    imageSrc: '/assets/reviews/rating-picture-3.png',
    title: 'Dissecting Ruby on Rails 5',
    author: 'Mark Essien',
    avgRating: 4.7,
    ratingNo: 123,
    price: 7500,
  },
  {
    id: 5,
    imageSrc: '/assets/reviews/rating-picture-3.png',
    title: 'Dissecting Ruby on Rails 5',
    author: 'Mark Essien',
    avgRating: 4.7,
    ratingNo: 123,
    price: 7500,
  },
];
