import { Products } from '../../@types';

export const staticProducts: Products[] = [
  {
    id: '1',
    name: 'Book',
    price: 100,
    shopOwner: 'Mark Essien',
    image: '/assets/cartimage.png',
    category: 'Category 1',
  },
  {
    id: '2',
    name: 'Webinar and Course Template',
    price: 100,
    shopOwner: 'Mark Essien',
    image: '/assets/carttwo.png',
    category: 'Category 2',
  },
  {
    id: '3',
    name: 'Webinar and Course Template',
    price: 100,
    shopOwner: 'Mark Essien',
    image: '/assets/cardthree.png',
    category: 'Category 3',
  },
  {
    id: '4',
    name: 'Webinar and Course Template',
    price: 100,
    shopOwner: 'Mark Essien',
    image: '/assets/card5.png',
    category: 'Category 4',
  },
  {
    id: '5',
    name: 'Webinar and Course Template',
    price: 100,
    shopOwner: 'Mark Essien',
    image: '/assets/wishlistAssets/favProductImg3.png',
    category: 'Category 5',
  },
  {
    id: '6',
    name: 'Webinar and Course Template',
    price: 100,
    shopOwner: 'Mark Essien',
    image: '/assets/wishlistAssets/favProductImg6.png',
    category: 'Category 6',
  },
  {
    id: '7',
    name: 'Webinar and Course Template',
    price: 100,
    shopOwner: 'Mark Essien',
    image: '/assets/wishlistAssets/favProductImg5.png',
    category: 'Category 7',
  },
  {
    id: '8',
    name: 'Webinar and Course Template',
    price: 100,
    shopOwner: 'Mark Essien',
    image: '/assets/wishlistAssets/favProductImg2.png',
    category: 'Category 8',
  },
  {
    id: '9',
    name: 'Webinar and Course Template',
    price: 100,
    shopOwner: 'Mark Essien',
    image: '/assets/wishlistAssets/favProductImg4.png',
    category: 'Category 9',
  },
  {
    id: '10',
    name: 'Webinar and Course Template',
    price: 100,
    shopOwner: 'Mark Essien',
    image: '/assets/wishlistAssets/favProductImg1.png',
    category: 'Category 10',
  },
  {
    id: '11',
    name: 'Webinar and Course Template',
    price: 100,
    shopOwner: 'Mark Essien',
    image: '/assets/wishlistAssets/favProductImg6.png',
    category: 'Category 11',
  },
  {
    id: '12',
    name: 'Webinar and Course Template',
    price: 100,
    shopOwner: 'Mark Essien',
    image: '/assets/wishlistAssets/favProductImg5.png',
    category: 'Category 12',
  },
  {
    id: '13',
    name: 'Webinar and Course Template',
    price: 100,
    shopOwner: 'Mark Essien',
    image: '/assets/wishlistAssets/favProductImg7.png',
    category: 'Category 13',
  },
  {
    id: '14',
    name: 'Webinar and Course Template',
    price: 100,
    shopOwner: 'Mark Essien',
    image: '/assets/wishlistAssets/favProductImg2.png',
    category: 'Category 14',
  },
  {
    id: '15',
    name: 'Webinar and Course Template',
    price: 100,
    shopOwner: 'Mark Essien',
    image: '/assets/wishlistAssets/favProductImg4.png',
    category: 'Category 15',
  },
  {
    id: '16',
    name: 'Webinar and Course Template',
    price: 100,
    shopOwner: 'Mark Essien',
    image: '/assets/wishlistAssets/favProductImg5.png',
    category: 'Category 16',
  },
  {
    id: '17',
    name: 'Webinar and Course Template',
    price: 100,
    shopOwner: 'Mark Essien',
    image: '/assets/wishlistAssets/favProductImg3.png',
    category: 'Category 17',
  },
  {
    id: '18',
    name: 'Webinar and Course Template',
    price: 100,
    shopOwner: 'Mark Essien',
    image: '/assets/wishlistAssets/favProductImg1.png',
    category: 'Category 18',
  },
  {
    id: '19',
    name: 'Webinar and Course Template',
    price: 100,
    shopOwner: 'Mark Essien',
    image: '/assets/wishlistAssets/favProductImg6.png',
    category: 'Category 19',
  },
  {
    id: '20',
    name: 'Webinar and Course Template',
    price: 100,
    shopOwner: 'Mark Essien',
    image: '/assets/wishlistAssets/favProductImg7.png',
    category: 'Category 20',
  },
];
