import { Products } from '../../@types';

export const staticProducts: Products[] = [
  {
    _id: '1',
    name: 'Book',
    price: 100,
    shopOwner: 'Mark Essien',
    image: '/assets/slider1.png',
    category: 'Category 1',
    specification: 'Hi',
    description: 'hi',
    rating: 5,
  },
  {
    _id: '2',
    name: 'Webinar and Course Template',
    price: 100,
    shopOwner: 'Mark Essien',
    image: '/assets/slider2.png',
    category: 'Category 2',
    specification: 'Hi',
    description: 'hi',
    rating: 5,
  },
  {
    _id: '3',
    name: 'Webinar and Course Template',
    price: 100,
    shopOwner: 'Mark Essien',
    image: '/assets/slider3.png',
    category: 'Category 3',
    specification: 'Hi',
    description: 'hi',
    rating: 5,
  },
  {
    _id: '4',
    name: 'Webinar and Course Template',
    price: 100,
    shopOwner: 'Mark Essien',
    image: '/assets/slider4.png',
    category: 'Category 4',
    specification: 'Hi',
    description: 'hi',
    rating: 5,
  },
  {
    _id: '5',
    name: 'Webinar and Course Template',
    price: 100,
    shopOwner: 'Mark Essien',
    image: '/assets/slider5.png',
    category: 'Category 5',
    specification: 'Hi',
    description: 'hi',
    rating: 5,
  },
  {
    _id: '6',
    name: 'Webinar and Course Template',
    price: 100,
    shopOwner: 'Mark Essien',
    image: '/assets/slider1.png',
    category: 'Category 6',
    specification: 'Hi',
    description: 'hi',
    rating: 5,
  },
  {
    _id: '7',
    name: 'Webinar and Course Template',
    price: 100,
    shopOwner: 'Mark Essien',
    image: '/assets/slider2.png',
    category: 'Category 7',
    specification: 'Hi',
    description: 'hi',
    rating: 5,
  },
];
