export const questionArr = [
  {
    id: 1,
    click: 'first',
    question: "What is the primary goal of a 'landing' page in digital marketing?",
    tip: 'Pick only one correct answer',
    options: [
      'To provide customer support',
      "To showcase the company's history",
      'To collect visitor information or encourage a specific action',
      'To display a blog',
    ],
  },
  {
    id: 2,
    click: 'second',
    question: 'In digital marketing, a higher bounce rate on a website is always a negative indicator of performance.',
    tip: 'Choose either true of false',
    options: ['True', 'False', 'None', 'i dont know'],
  },
  {
    id: 3,
    click: 'third',
    question: 'What is the primary goal of a &apos;landing page&apos; in digital marketing?',
    tip: 'Pick only one correct answer',
    options: [
      'To provide customer support',
      "To showcase the company's history",
      'To collect visitor information or encourage a specific action',
      'To display a blog',
    ],
  },
  {
    id: 4,
    click: 'fourth',
    question: 'In digital marketing, a higher bounce rate on a website is always a negative indicator of performance.',
    tip: 'Choose either true of false',
    options: ['True', 'False', 'None', 'i dont know'],
  },
  {
    id: 5,
    click: 'fifth',
    question: 'What is the primary goal of a &apos;landing page&apos; in digital marketing?',
    tip: 'Pick only one correct answer',
    options: [
      'To provide customer support',
      "To showcase the company's history",
      'To collect visitor information or encourage a specific action',
      'To display a blog',
    ],
  },
  {
    id: 6,
    click: 'sixth',
    question: 'In digital marketing, a higher bounce rate on a website is always a negative indicator of performance.',
    tip: 'Choose either true of false',
    options: ['True', 'False', 'None', 'i dont know'],
  },
  {
    id: 7,
    click: 'sevth',
    question: 'What is the primary goal of a &apos;landing page&apos; in digital marketing?',
    tip: 'Pick only one correct answer',
    options: [
      'To provide customer support',
      "To showcase the company's history",
      'To collect visitor information or encourage a specific action',
      'To display a blog',
    ],
  },
  {
    id: 8,
    click: 'eight',
    question: 'In digital marketing, a higher bounce rate on a website is always a negative indicator of performance.',
    tip: 'Choose either true of false',
    options: ['True', 'False', 'None', 'i dont know'],
  },
  {
    id: 9,
    click: 'nine',
    question: 'What is the primary goal of a &apos;landing page&apos; in digital marketing?',
    tip: 'Pick only one correct answer',
    options: [
      'To provide customer support',
      "To showcase the company's history",
      'To collect visitor information or encourage a specific action',
      'To display a blog',
    ],
  },
  {
    id: 10,
    click: 'ten',
    question: 'In digital marketing, a higher bounce rate on a website is always a negative indicator of performance.',
    tip: 'Choose either true of false',
    options: ['True', 'False', 'None', 'i dont know'],
  },
];
