---
name: Zuri main dev Deployment

on:
  # push:
  #   branches:
  #     - dev
  pull_request:
    branches: [dev]
  # schedule:
  # cron job that runs every 2 minutes
  # - cron: '* * * '

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: build app
        run: |
          yarn install
          yarn build
