---
name: Zuri main dev Deployment

on:
  push:
    branches:
      - dev
  # pull_request:
  # branches: [dev]
  # schedule:
  # cron job that runs every 2 minutes
  # - cron: '* * * '

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: build app
        run: |
          yarn install
          yarn build

  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    needs: build
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: build again
        run: |
          yarn install
          yarn build
          rm -rf node_modules

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-without-markdown
          path: |
            dist
            !dist/**/*.md

      - name: Copy build folder to server
        uses: Creepios/sftp-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST_STAGING }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.DEPLOY_PORT }}
          localPath: './'
          remotePath: '/home/devops/zuri_frontend/zuriportfolio-frontend/'

      - name: ssh scp ssh pipelines
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          host: ${{ secrets.DEPLOY_HOST_STAGING }}
          user: ${{ secrets.USERNAME }}
          pass: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          first_ssh: |
            su - devops
            cd /home/devops/zuri_frontend/zuriportfolio-frontend
            yarn install --ignore-engines
            pm2 restart zuri_frontend
